services:
  db:
    image: postgres:17-alpine
    container_name: postgres_autoflex
    restart: always
    environment:
      POSTGRES_DB: materials_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toky
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: autoflex_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/materials_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: toky

volumes:
  postgres_data: