services:
  db:
    image: postgres:17-alpine
    container_name: postgres_autoflex
    restart: always
    environment:
      POSTGRES_DB: materials_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toky
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: